### ISSUE TITLE
Bug Repo gibt es nicht

### ISSUE THREAD

**Issue by BulldozerPete** [RPiList/MyDockerCompose#1]
Hallo Sprecher,

das ausführen der yaml führt zu folgendem Fehler:

failed to deploy a stack: breitband-desktop Pulling breitband-desktop Error Error response from daemon: pull access denied for breitband, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by geimist** [comment]
Hier ist das Repo:
https://github.com/fabianbees/breitbandmessung-docker

Im Terminal:
```
git clone https://github.com/fabianbees/breitbandmessung-docker.git
cd breitbandmessung-docker
docker build -t breitband:latest .
```   

Anschließend den Container starten:
```
docker run -d \
    --name breitband-desktop \
    -e TZ=Europe/Berlin \
    -v $PWD/breitbandmessung/data:/config/xdg/config/Breitbandmessung \
    -p 5800:5800 \
    breitband:latest
```

**Comment by RPiList** [comment]
> Hallo Sprecher,
> 
> das ausführen der yaml führt zu folgendem Fehler:
> 
> failed to deploy a stack: breitband-desktop Pulling breitband-desktop Error Error response from daemon: pull access denied for breitband, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

die Datei wurde aktualisiert, damit sollte der Fehler erledigt sein. Viele Grüße
