### ISSUE TITLE
Deployment issue

### ISSUE THREAD

**Issue by BulldozerPete** [RPiList/MyDockerCompose#2]
Beim Deployment bekomme ich folgenden Fehler:

`Deployment error
failed to deploy a stack: breitband-desktop Pulling breitband-desktop Warning failed to solve: failed to read dockerfile: failed to load cache key: failed to init repo at /var/lib/docker/overlay2/sevolrccuo9zpdkpc4aelgnto/diff: exec: "git": executable file not found in $PATH`

**Comment by LizenzFass78851** [comment]
Versuche auf dem Docker Rechner / VM `git` zu installieren.

- Für Debian / Ubuntu
`apt install git -y`

Vielleicht lag es mit etwas Glück daran.

**Comment by RPiList** [comment]
Ja, die Info wurde bereits unter das entsprechende Video gepackt. Offenbar wird git benötigt, dass mein "Ubuntu" aber wohl schon hatte. Debian-User müssen das evtl. von Hand nachinstallieren.
